version: '3.9'

services:
  db:
    image: postgres:16
    container_name: characters_library_postgres
    environment:
      POSTGRES_USER: vdemc
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CharactersLibraryDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: