// <auto-generated />
using System;
using CharactersLibraryWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CharactersLibraryWebApp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260518015208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharactersLibraryWebApp.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("WeaponTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The 77th Director of the Wangsheng Funeral Parlor.",
                            ElementId = 1,
                            Name = "Hu Tao",
                            Rarity = 5,
                            ReleaseDate = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Director of the Wangsheng Funeral Parlor",
                            WeaponTypeId = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Her Excellency, the Almighty Narukami Ogosho.",
                            ElementId = 4,
                            Name = "Raiden Shogun",
                            Rarity = 5,
                            ReleaseDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Plane of Euthymia",
                            WeaponTypeId = 5
                        });
                });

            modelBuilder.Entity("CharactersLibraryWebApp.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF4500",
                            Name = "Pyro"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#1E90FF",
                            Name = "Hydro"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#00CED1",
                            Name = "Anemo"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#9400D3",
                            Name = "Electro"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#228B22",
                            Name = "Dendro"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#ADD8E6",
                            Name = "Cryo"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#FFD700",
                            Name = "Geo"
                        });
                });

            modelBuilder.Entity("CharactersLibraryWebApp.Models.Talent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TalentType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("CharactersLibraryWebApp.Models.WeaponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeaponTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sword"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bow"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Catalyst"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Claymore"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Polearm"
                        });
                });

            modelBuilder.Entity("CharactersLibraryWebApp.Models.Character", b =>
                {
                    b.HasOne("CharactersLibraryWebApp.Models.Element", "Element")
                        .WithMany("Characters")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharactersLibraryWebApp.Models.WeaponType", "WeaponType")
                        .WithMany("Characters")
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("CharactersLibraryWebApp.Models.Talent", b =>
                {
                    b.HasOne("CharactersLibraryWebApp.Models.Character", "Character")
                        .WithMany("Talents")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("CharactersLibraryWebApp.Models.Character", b =>
                {
                    b.Navigation("Talents");
                });

            modelBuilder.Entity("CharactersLibraryWebApp.Models.Element", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("CharactersLibraryWebApp.Models.WeaponType", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
